# Generated by Django 4.1.2 on 2022-10-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorSummernote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manuais',
            table='Manuais',
        ),
    ]
