# Generated by Django 4.1.2 on 2022-10-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorSummernote', '0002_alter_manuais_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuais',
            name='tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
